### ISSUE TITLE
R5 Postman Testing for #6: View all active sessions

### ISSUE THREAD

**Issue by PLangari** [JMatt26/StuddyBuddy#40]
Sprint A Requirement 5: Backend.

Estimated time : 0.25 H.

this is a postman test: not an integration test

**Comment by savperera369** [comment]
Finished this one. Took way longer than expected due to the deprecated methods of the date class.

Estimated Time: 0.75h
Actual Time: 2.5h

**Comment by savperera369** [comment]
Estimated Time: 0.75h
Actual Time: 0.75h
