### ISSUE TITLE
R13 GET Endpoint: Return all the sessions that have at least 1 tag in a given set of searched tags.

### ISSUE THREAD

**Issue by PLangari** [JMatt26/StuddyBuddy#60]
Sprint A Requirement 18: Backend.

Estimated Time: 0.5 H.

Note:
The tags/categories itself can be either a List of Strings, or a class itself.
Please add the tags/categories attribute in the SessionInformation class rather than the Session class.

**Comment by KristianMyzeqari** [comment]
Actual time: 1h30
