### ISSUE TITLE
R5 Frontend: Make a component that displays all the active/upcoming sessions.

### ISSUE THREAD

**Issue by PLangari** [JMatt26/StuddyBuddy#70]
Sprint A Requirement 5: Frontend.

Estimated time: 2.5 Hours.

Note: Make a carousel with cards that display information about a session -- please reference figma for styling.
![Screenshot 2023-02-22 at 4 47 55 PM](https://user-images.githubusercontent.com/85724076/220766944-ac3078bb-ee3f-43d6-8290-73e755a0046c.png)

**Comment by jastaggart** [comment]
Actual time: 2.5h
