### ISSUE TITLE
Assemble home page with already made components required to make the page

### ISSUE THREAD

**Issue by PLangari** [JMatt26/StuddyBuddy#76]
Assemble all the components in the main page.

Time estimate : 0.5 H

One way to do it:
- Make a vertical ScrollView component for the page.
- Make sure to have { display : "flex" } inside the style of the above container.
- Insert all the (already made) components of the home page inside the ScrollView component in the correct order.
- For all the containers/components directly inside the ScrollView, make sure they have { flex : 1 } inside their style.

**Comment by KristianMyzeqari** [comment]
Actual time: 1h 15 minutes
